# Generated by Django 2.2.17 on 2021-03-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='ReserveDateTime',
            field=models.CharField(max_length=20),
        ),
    ]
