# Generated by Django 2.2.17 on 2021-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0002_auto_20210304_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='ReserveDateTime',
            field=models.TextField(max_length=20),
        ),
    ]
